// This file is auto-generated by Athena. Do not edit.

export const activePlugins = [
  {
    name: "calendar",
    pkgName: "athena-plugin-calendar",
    isLocal: true,
    module: () => import("athena-plugin-calendar")
  },
  {
    name: "mail",
    pkgName: "athena-plugin-mail",
    isLocal: true,
    module: () => import("athena-plugin-mail")
  },
  {
    name: "map",
    pkgName: "athena-plugin-map",
    isLocal: true,
    module: () => import("athena-plugin-map")
  },
  {
    name: "morning",
    pkgName: "athena-plugin-morning",
    isLocal: true,
    module: () => import("athena-plugin-morning")
  },
  {
    name: "tasks",
    pkgName: "athena-plugin-tasks",
    isLocal: true,
    module: () => import("athena-plugin-tasks")
  },
  {
    name: "weather",
    pkgName: "athena-plugin-weather",
    isLocal: true,
    module: () => import("athena-plugin-weather")
  },
];
