import fs from "node:fs";
import path from "node:path";
import { findProjectRoot } from "@/lib/utils/workspace";

export function generateManifest() {
	const rootDir = findProjectRoot();
	const packageJsonPath = path.join(rootDir, "package.json");

	if (!fs.existsSync(packageJsonPath)) {
		console.warn(`[Plugins] package.json not found at ${packageJsonPath}`);
		return;
	}

	try {
		const pkg = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));
		const deps = {
			...(pkg.dependencies || {}),
			...(pkg.devDependencies || {}),
		};

		const pluginDeps = Object.entries(deps)
			.filter(([name]) => name.startsWith("athena-plugin-") || name.startsWith("@athena/plugin-"))
			.map(([name, value]) => ({
				pkgName: name,
				isLocal: value === "workspace:*",
				shortName: name.startsWith("athena-plugin-")
					? name.replace("athena-plugin-", "")
					: name.replace("@athena/plugin-", ""),
			}));

		const manifestPath = path.join(rootDir, "lib", "plugins", "manifest.ts");

		let content = "// This file is auto-generated by Athena. Do not edit.\n";
		content += "\nexport const activePlugins = [\n";

		pluginDeps.forEach((dep) => {
			content += `  {\n`;
			content += `    name: "${dep.shortName}",\n`;
			content += `    pkgName: "${dep.pkgName}",\n`;
			content += `    isLocal: ${dep.isLocal},\n`;
			content += `    module: () => import("${dep.pkgName}")\n`;
			content += `  },\n`;
		});

		content += "];\n";

		// Ensure parent directories exist
		const parentDir = path.dirname(manifestPath);
		if (!fs.existsSync(parentDir)) {
			fs.mkdirSync(parentDir, { recursive: true });
		}

		fs.writeFileSync(manifestPath, content, "utf-8");
		console.log(`[Plugins] Manifest generated successfully at ${manifestPath} with ${pluginDeps.length} plugins.`);
	} catch (error) {
		console.error("[Plugins] Failed to generate manifest:", error);
	}
}
